services:
  - type: web
    name: postgres-proyecto-comerciantes-costeros
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.postgres
    autoDeploy: true
    envVars:
      - key: POSTGRES_USER
        value: user
      - key: POSTGRES_PASSWORD
        value: 1234
      - key: POSTGRES_DB
        value: miapp
    volumes:
      - name: db_data
        mountPath: /var/lib/postgresql/data
        sizeGB: 20

  - type: web
    name: api-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.api
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DB_HOST
        value: postgres-proyecto-comerciantes-costeros
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: user
      - key: DB_PASSWORD
        value: 1234
      - key: DB_NAME
        value: miapp

  - type: web
    name: pgadmin
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.pgadmin
    autoDeploy: true
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
    volumes:
      - name: pgadmin_data
        mountPath: /var/lib/pgadmin
        sizeGB: 1
